[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
logfile=/data/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info

[program:omniparser-api]
command=/opt/program/init.sh uvicorn api_service:app --host 0.0.0.0 --port 8080 --workers 1
directory=/opt/program
autostart=true
autorestart=true
stderr_logfile=/data/logs/omniparser-api-error.log
stdout_logfile=/data/logs/omniparser-api.log
stderr_logfile_maxbytes=10MB
stdout_logfile_maxbytes=10MB
user=root
environment=PYTHONPATH="/opt/program" 